/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedDashboardUsersRouteImport } from './routes/_authenticated/dashboard.users'
import { Route as AuthenticatedDashboardTasksRouteImport } from './routes/_authenticated/dashboard.tasks'
import { Route as AuthenticatedDashboardOfficersRouteImport } from './routes/_authenticated/dashboard.officers'
import { Route as AuthenticatedDashboardNotificationsRouteImport } from './routes/_authenticated/dashboard.notifications'
import { Route as AuthenticatedDashboardMyWorkRouteImport } from './routes/_authenticated/dashboard.my-work'
import { Route as AuthenticatedDashboardLocationsRouteImport } from './routes/_authenticated/dashboard.locations'
import { Route as AuthenticatedDashboardTasksIndexRouteImport } from './routes/_authenticated/dashboard.tasks.index'
import { Route as AuthenticatedDashboardOfficersIndexRouteImport } from './routes/_authenticated/dashboard.officers.index'
import { Route as AuthenticatedDashboardLocationsIndexRouteImport } from './routes/_authenticated/dashboard.locations.index'
import { Route as AuthenticatedDashboardFieldReportsIndexRouteImport } from './routes/_authenticated/dashboard.field-reports.index'
import { Route as AuthenticatedDashboardTasksPrintRouteImport } from './routes/_authenticated/dashboard.tasks.print'
import { Route as AuthenticatedDashboardTasksNewRouteImport } from './routes/_authenticated/dashboard.tasks.new'
import { Route as AuthenticatedDashboardTasksTaskIdRouteImport } from './routes/_authenticated/dashboard.tasks.$taskId'
import { Route as AuthenticatedDashboardReportsPrintRouteImport } from './routes/_authenticated/dashboard.reports.print'
import { Route as AuthenticatedDashboardOfficersPrintRouteImport } from './routes/_authenticated/dashboard.officers.print'
import { Route as AuthenticatedDashboardOfficersUserIdRouteImport } from './routes/_authenticated/dashboard.officers.$userId'
import { Route as AuthenticatedDashboardLocationsPrintRouteImport } from './routes/_authenticated/dashboard.locations.print'
import { Route as AuthenticatedDashboardLocationsLocationIdRouteImport } from './routes/_authenticated/dashboard.locations.$locationId'
import { Route as AuthenticatedDashboardTasksTaskIdEditRouteImport } from './routes/_authenticated/dashboard.tasks.$taskId.edit'
import { Route as AuthenticatedDashboardTasksTaskIdReportsNewRouteImport } from './routes/_authenticated/dashboard.tasks.$taskId.reports.new'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardUsersRoute =
  AuthenticatedDashboardUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTasksRoute =
  AuthenticatedDashboardTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOfficersRoute =
  AuthenticatedDashboardOfficersRouteImport.update({
    id: '/officers',
    path: '/officers',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardNotificationsRoute =
  AuthenticatedDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMyWorkRoute =
  AuthenticatedDashboardMyWorkRouteImport.update({
    id: '/my-work',
    path: '/my-work',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardLocationsRoute =
  AuthenticatedDashboardLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTasksIndexRoute =
  AuthenticatedDashboardTasksIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardTasksRoute,
  } as any)
const AuthenticatedDashboardOfficersIndexRoute =
  AuthenticatedDashboardOfficersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardOfficersRoute,
  } as any)
const AuthenticatedDashboardLocationsIndexRoute =
  AuthenticatedDashboardLocationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardLocationsRoute,
  } as any)
const AuthenticatedDashboardFieldReportsIndexRoute =
  AuthenticatedDashboardFieldReportsIndexRouteImport.update({
    id: '/field-reports/',
    path: '/field-reports/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTasksPrintRoute =
  AuthenticatedDashboardTasksPrintRouteImport.update({
    id: '/print',
    path: '/print',
    getParentRoute: () => AuthenticatedDashboardTasksRoute,
  } as any)
const AuthenticatedDashboardTasksNewRoute =
  AuthenticatedDashboardTasksNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedDashboardTasksRoute,
  } as any)
const AuthenticatedDashboardTasksTaskIdRoute =
  AuthenticatedDashboardTasksTaskIdRouteImport.update({
    id: '/$taskId',
    path: '/$taskId',
    getParentRoute: () => AuthenticatedDashboardTasksRoute,
  } as any)
const AuthenticatedDashboardReportsPrintRoute =
  AuthenticatedDashboardReportsPrintRouteImport.update({
    id: '/reports/print',
    path: '/reports/print',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOfficersPrintRoute =
  AuthenticatedDashboardOfficersPrintRouteImport.update({
    id: '/print',
    path: '/print',
    getParentRoute: () => AuthenticatedDashboardOfficersRoute,
  } as any)
const AuthenticatedDashboardOfficersUserIdRoute =
  AuthenticatedDashboardOfficersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedDashboardOfficersRoute,
  } as any)
const AuthenticatedDashboardLocationsPrintRoute =
  AuthenticatedDashboardLocationsPrintRouteImport.update({
    id: '/print',
    path: '/print',
    getParentRoute: () => AuthenticatedDashboardLocationsRoute,
  } as any)
const AuthenticatedDashboardLocationsLocationIdRoute =
  AuthenticatedDashboardLocationsLocationIdRouteImport.update({
    id: '/$locationId',
    path: '/$locationId',
    getParentRoute: () => AuthenticatedDashboardLocationsRoute,
  } as any)
const AuthenticatedDashboardTasksTaskIdEditRoute =
  AuthenticatedDashboardTasksTaskIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedDashboardTasksTaskIdRoute,
  } as any)
const AuthenticatedDashboardTasksTaskIdReportsNewRoute =
  AuthenticatedDashboardTasksTaskIdReportsNewRouteImport.update({
    id: '/reports/new',
    path: '/reports/new',
    getParentRoute: () => AuthenticatedDashboardTasksTaskIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/dashboard/locations': typeof AuthenticatedDashboardLocationsRouteWithChildren
  '/dashboard/my-work': typeof AuthenticatedDashboardMyWorkRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/officers': typeof AuthenticatedDashboardOfficersRouteWithChildren
  '/dashboard/tasks': typeof AuthenticatedDashboardTasksRouteWithChildren
  '/dashboard/users': typeof AuthenticatedDashboardUsersRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/locations/$locationId': typeof AuthenticatedDashboardLocationsLocationIdRoute
  '/dashboard/locations/print': typeof AuthenticatedDashboardLocationsPrintRoute
  '/dashboard/officers/$userId': typeof AuthenticatedDashboardOfficersUserIdRoute
  '/dashboard/officers/print': typeof AuthenticatedDashboardOfficersPrintRoute
  '/dashboard/reports/print': typeof AuthenticatedDashboardReportsPrintRoute
  '/dashboard/tasks/$taskId': typeof AuthenticatedDashboardTasksTaskIdRouteWithChildren
  '/dashboard/tasks/new': typeof AuthenticatedDashboardTasksNewRoute
  '/dashboard/tasks/print': typeof AuthenticatedDashboardTasksPrintRoute
  '/dashboard/field-reports/': typeof AuthenticatedDashboardFieldReportsIndexRoute
  '/dashboard/locations/': typeof AuthenticatedDashboardLocationsIndexRoute
  '/dashboard/officers/': typeof AuthenticatedDashboardOfficersIndexRoute
  '/dashboard/tasks/': typeof AuthenticatedDashboardTasksIndexRoute
  '/dashboard/tasks/$taskId/edit': typeof AuthenticatedDashboardTasksTaskIdEditRoute
  '/dashboard/tasks/$taskId/reports/new': typeof AuthenticatedDashboardTasksTaskIdReportsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/my-work': typeof AuthenticatedDashboardMyWorkRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/users': typeof AuthenticatedDashboardUsersRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/locations/$locationId': typeof AuthenticatedDashboardLocationsLocationIdRoute
  '/dashboard/locations/print': typeof AuthenticatedDashboardLocationsPrintRoute
  '/dashboard/officers/$userId': typeof AuthenticatedDashboardOfficersUserIdRoute
  '/dashboard/officers/print': typeof AuthenticatedDashboardOfficersPrintRoute
  '/dashboard/reports/print': typeof AuthenticatedDashboardReportsPrintRoute
  '/dashboard/tasks/$taskId': typeof AuthenticatedDashboardTasksTaskIdRouteWithChildren
  '/dashboard/tasks/new': typeof AuthenticatedDashboardTasksNewRoute
  '/dashboard/tasks/print': typeof AuthenticatedDashboardTasksPrintRoute
  '/dashboard/field-reports': typeof AuthenticatedDashboardFieldReportsIndexRoute
  '/dashboard/locations': typeof AuthenticatedDashboardLocationsIndexRoute
  '/dashboard/officers': typeof AuthenticatedDashboardOfficersIndexRoute
  '/dashboard/tasks': typeof AuthenticatedDashboardTasksIndexRoute
  '/dashboard/tasks/$taskId/edit': typeof AuthenticatedDashboardTasksTaskIdEditRoute
  '/dashboard/tasks/$taskId/reports/new': typeof AuthenticatedDashboardTasksTaskIdReportsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/download': typeof DownloadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/dashboard/locations': typeof AuthenticatedDashboardLocationsRouteWithChildren
  '/_authenticated/dashboard/my-work': typeof AuthenticatedDashboardMyWorkRoute
  '/_authenticated/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/_authenticated/dashboard/officers': typeof AuthenticatedDashboardOfficersRouteWithChildren
  '/_authenticated/dashboard/tasks': typeof AuthenticatedDashboardTasksRouteWithChildren
  '/_authenticated/dashboard/users': typeof AuthenticatedDashboardUsersRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/locations/$locationId': typeof AuthenticatedDashboardLocationsLocationIdRoute
  '/_authenticated/dashboard/locations/print': typeof AuthenticatedDashboardLocationsPrintRoute
  '/_authenticated/dashboard/officers/$userId': typeof AuthenticatedDashboardOfficersUserIdRoute
  '/_authenticated/dashboard/officers/print': typeof AuthenticatedDashboardOfficersPrintRoute
  '/_authenticated/dashboard/reports/print': typeof AuthenticatedDashboardReportsPrintRoute
  '/_authenticated/dashboard/tasks/$taskId': typeof AuthenticatedDashboardTasksTaskIdRouteWithChildren
  '/_authenticated/dashboard/tasks/new': typeof AuthenticatedDashboardTasksNewRoute
  '/_authenticated/dashboard/tasks/print': typeof AuthenticatedDashboardTasksPrintRoute
  '/_authenticated/dashboard/field-reports/': typeof AuthenticatedDashboardFieldReportsIndexRoute
  '/_authenticated/dashboard/locations/': typeof AuthenticatedDashboardLocationsIndexRoute
  '/_authenticated/dashboard/officers/': typeof AuthenticatedDashboardOfficersIndexRoute
  '/_authenticated/dashboard/tasks/': typeof AuthenticatedDashboardTasksIndexRoute
  '/_authenticated/dashboard/tasks/$taskId/edit': typeof AuthenticatedDashboardTasksTaskIdEditRoute
  '/_authenticated/dashboard/tasks/$taskId/reports/new': typeof AuthenticatedDashboardTasksTaskIdReportsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/download'
    | '/reset-password'
    | '/sitemap.xml'
    | '/dashboard'
    | '/dashboard/locations'
    | '/dashboard/my-work'
    | '/dashboard/notifications'
    | '/dashboard/officers'
    | '/dashboard/tasks'
    | '/dashboard/users'
    | '/dashboard/'
    | '/dashboard/locations/$locationId'
    | '/dashboard/locations/print'
    | '/dashboard/officers/$userId'
    | '/dashboard/officers/print'
    | '/dashboard/reports/print'
    | '/dashboard/tasks/$taskId'
    | '/dashboard/tasks/new'
    | '/dashboard/tasks/print'
    | '/dashboard/field-reports/'
    | '/dashboard/locations/'
    | '/dashboard/officers/'
    | '/dashboard/tasks/'
    | '/dashboard/tasks/$taskId/edit'
    | '/dashboard/tasks/$taskId/reports/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/download'
    | '/reset-password'
    | '/sitemap.xml'
    | '/dashboard/my-work'
    | '/dashboard/notifications'
    | '/dashboard/users'
    | '/dashboard'
    | '/dashboard/locations/$locationId'
    | '/dashboard/locations/print'
    | '/dashboard/officers/$userId'
    | '/dashboard/officers/print'
    | '/dashboard/reports/print'
    | '/dashboard/tasks/$taskId'
    | '/dashboard/tasks/new'
    | '/dashboard/tasks/print'
    | '/dashboard/field-reports'
    | '/dashboard/locations'
    | '/dashboard/officers'
    | '/dashboard/tasks'
    | '/dashboard/tasks/$taskId/edit'
    | '/dashboard/tasks/$taskId/reports/new'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/download'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/dashboard/locations'
    | '/_authenticated/dashboard/my-work'
    | '/_authenticated/dashboard/notifications'
    | '/_authenticated/dashboard/officers'
    | '/_authenticated/dashboard/tasks'
    | '/_authenticated/dashboard/users'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/locations/$locationId'
    | '/_authenticated/dashboard/locations/print'
    | '/_authenticated/dashboard/officers/$userId'
    | '/_authenticated/dashboard/officers/print'
    | '/_authenticated/dashboard/reports/print'
    | '/_authenticated/dashboard/tasks/$taskId'
    | '/_authenticated/dashboard/tasks/new'
    | '/_authenticated/dashboard/tasks/print'
    | '/_authenticated/dashboard/field-reports/'
    | '/_authenticated/dashboard/locations/'
    | '/_authenticated/dashboard/officers/'
    | '/_authenticated/dashboard/tasks/'
    | '/_authenticated/dashboard/tasks/$taskId/edit'
    | '/_authenticated/dashboard/tasks/$taskId/reports/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DownloadRoute: typeof DownloadRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/users': {
      id: '/_authenticated/dashboard/users'
      path: '/users'
      fullPath: '/dashboard/users'
      preLoaderRoute: typeof AuthenticatedDashboardUsersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/tasks': {
      id: '/_authenticated/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof AuthenticatedDashboardTasksRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/officers': {
      id: '/_authenticated/dashboard/officers'
      path: '/officers'
      fullPath: '/dashboard/officers'
      preLoaderRoute: typeof AuthenticatedDashboardOfficersRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/notifications': {
      id: '/_authenticated/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof AuthenticatedDashboardNotificationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/my-work': {
      id: '/_authenticated/dashboard/my-work'
      path: '/my-work'
      fullPath: '/dashboard/my-work'
      preLoaderRoute: typeof AuthenticatedDashboardMyWorkRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/locations': {
      id: '/_authenticated/dashboard/locations'
      path: '/locations'
      fullPath: '/dashboard/locations'
      preLoaderRoute: typeof AuthenticatedDashboardLocationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/tasks/': {
      id: '/_authenticated/dashboard/tasks/'
      path: '/'
      fullPath: '/dashboard/tasks/'
      preLoaderRoute: typeof AuthenticatedDashboardTasksIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardTasksRoute
    }
    '/_authenticated/dashboard/officers/': {
      id: '/_authenticated/dashboard/officers/'
      path: '/'
      fullPath: '/dashboard/officers/'
      preLoaderRoute: typeof AuthenticatedDashboardOfficersIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardOfficersRoute
    }
    '/_authenticated/dashboard/locations/': {
      id: '/_authenticated/dashboard/locations/'
      path: '/'
      fullPath: '/dashboard/locations/'
      preLoaderRoute: typeof AuthenticatedDashboardLocationsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardLocationsRoute
    }
    '/_authenticated/dashboard/field-reports/': {
      id: '/_authenticated/dashboard/field-reports/'
      path: '/field-reports'
      fullPath: '/dashboard/field-reports/'
      preLoaderRoute: typeof AuthenticatedDashboardFieldReportsIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/tasks/print': {
      id: '/_authenticated/dashboard/tasks/print'
      path: '/print'
      fullPath: '/dashboard/tasks/print'
      preLoaderRoute: typeof AuthenticatedDashboardTasksPrintRouteImport
      parentRoute: typeof AuthenticatedDashboardTasksRoute
    }
    '/_authenticated/dashboard/tasks/new': {
      id: '/_authenticated/dashboard/tasks/new'
      path: '/new'
      fullPath: '/dashboard/tasks/new'
      preLoaderRoute: typeof AuthenticatedDashboardTasksNewRouteImport
      parentRoute: typeof AuthenticatedDashboardTasksRoute
    }
    '/_authenticated/dashboard/tasks/$taskId': {
      id: '/_authenticated/dashboard/tasks/$taskId'
      path: '/$taskId'
      fullPath: '/dashboard/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedDashboardTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedDashboardTasksRoute
    }
    '/_authenticated/dashboard/reports/print': {
      id: '/_authenticated/dashboard/reports/print'
      path: '/reports/print'
      fullPath: '/dashboard/reports/print'
      preLoaderRoute: typeof AuthenticatedDashboardReportsPrintRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/officers/print': {
      id: '/_authenticated/dashboard/officers/print'
      path: '/print'
      fullPath: '/dashboard/officers/print'
      preLoaderRoute: typeof AuthenticatedDashboardOfficersPrintRouteImport
      parentRoute: typeof AuthenticatedDashboardOfficersRoute
    }
    '/_authenticated/dashboard/officers/$userId': {
      id: '/_authenticated/dashboard/officers/$userId'
      path: '/$userId'
      fullPath: '/dashboard/officers/$userId'
      preLoaderRoute: typeof AuthenticatedDashboardOfficersUserIdRouteImport
      parentRoute: typeof AuthenticatedDashboardOfficersRoute
    }
    '/_authenticated/dashboard/locations/print': {
      id: '/_authenticated/dashboard/locations/print'
      path: '/print'
      fullPath: '/dashboard/locations/print'
      preLoaderRoute: typeof AuthenticatedDashboardLocationsPrintRouteImport
      parentRoute: typeof AuthenticatedDashboardLocationsRoute
    }
    '/_authenticated/dashboard/locations/$locationId': {
      id: '/_authenticated/dashboard/locations/$locationId'
      path: '/$locationId'
      fullPath: '/dashboard/locations/$locationId'
      preLoaderRoute: typeof AuthenticatedDashboardLocationsLocationIdRouteImport
      parentRoute: typeof AuthenticatedDashboardLocationsRoute
    }
    '/_authenticated/dashboard/tasks/$taskId/edit': {
      id: '/_authenticated/dashboard/tasks/$taskId/edit'
      path: '/edit'
      fullPath: '/dashboard/tasks/$taskId/edit'
      preLoaderRoute: typeof AuthenticatedDashboardTasksTaskIdEditRouteImport
      parentRoute: typeof AuthenticatedDashboardTasksTaskIdRoute
    }
    '/_authenticated/dashboard/tasks/$taskId/reports/new': {
      id: '/_authenticated/dashboard/tasks/$taskId/reports/new'
      path: '/reports/new'
      fullPath: '/dashboard/tasks/$taskId/reports/new'
      preLoaderRoute: typeof AuthenticatedDashboardTasksTaskIdReportsNewRouteImport
      parentRoute: typeof AuthenticatedDashboardTasksTaskIdRoute
    }
  }
}

interface AuthenticatedDashboardLocationsRouteChildren {
  AuthenticatedDashboardLocationsLocationIdRoute: typeof AuthenticatedDashboardLocationsLocationIdRoute
  AuthenticatedDashboardLocationsPrintRoute: typeof AuthenticatedDashboardLocationsPrintRoute
  AuthenticatedDashboardLocationsIndexRoute: typeof AuthenticatedDashboardLocationsIndexRoute
}

const AuthenticatedDashboardLocationsRouteChildren: AuthenticatedDashboardLocationsRouteChildren =
  {
    AuthenticatedDashboardLocationsLocationIdRoute:
      AuthenticatedDashboardLocationsLocationIdRoute,
    AuthenticatedDashboardLocationsPrintRoute:
      AuthenticatedDashboardLocationsPrintRoute,
    AuthenticatedDashboardLocationsIndexRoute:
      AuthenticatedDashboardLocationsIndexRoute,
  }

const AuthenticatedDashboardLocationsRouteWithChildren =
  AuthenticatedDashboardLocationsRoute._addFileChildren(
    AuthenticatedDashboardLocationsRouteChildren,
  )

interface AuthenticatedDashboardOfficersRouteChildren {
  AuthenticatedDashboardOfficersUserIdRoute: typeof AuthenticatedDashboardOfficersUserIdRoute
  AuthenticatedDashboardOfficersPrintRoute: typeof AuthenticatedDashboardOfficersPrintRoute
  AuthenticatedDashboardOfficersIndexRoute: typeof AuthenticatedDashboardOfficersIndexRoute
}

const AuthenticatedDashboardOfficersRouteChildren: AuthenticatedDashboardOfficersRouteChildren =
  {
    AuthenticatedDashboardOfficersUserIdRoute:
      AuthenticatedDashboardOfficersUserIdRoute,
    AuthenticatedDashboardOfficersPrintRoute:
      AuthenticatedDashboardOfficersPrintRoute,
    AuthenticatedDashboardOfficersIndexRoute:
      AuthenticatedDashboardOfficersIndexRoute,
  }

const AuthenticatedDashboardOfficersRouteWithChildren =
  AuthenticatedDashboardOfficersRoute._addFileChildren(
    AuthenticatedDashboardOfficersRouteChildren,
  )

interface AuthenticatedDashboardTasksTaskIdRouteChildren {
  AuthenticatedDashboardTasksTaskIdEditRoute: typeof AuthenticatedDashboardTasksTaskIdEditRoute
  AuthenticatedDashboardTasksTaskIdReportsNewRoute: typeof AuthenticatedDashboardTasksTaskIdReportsNewRoute
}

const AuthenticatedDashboardTasksTaskIdRouteChildren: AuthenticatedDashboardTasksTaskIdRouteChildren =
  {
    AuthenticatedDashboardTasksTaskIdEditRoute:
      AuthenticatedDashboardTasksTaskIdEditRoute,
    AuthenticatedDashboardTasksTaskIdReportsNewRoute:
      AuthenticatedDashboardTasksTaskIdReportsNewRoute,
  }

const AuthenticatedDashboardTasksTaskIdRouteWithChildren =
  AuthenticatedDashboardTasksTaskIdRoute._addFileChildren(
    AuthenticatedDashboardTasksTaskIdRouteChildren,
  )

interface AuthenticatedDashboardTasksRouteChildren {
  AuthenticatedDashboardTasksTaskIdRoute: typeof AuthenticatedDashboardTasksTaskIdRouteWithChildren
  AuthenticatedDashboardTasksNewRoute: typeof AuthenticatedDashboardTasksNewRoute
  AuthenticatedDashboardTasksPrintRoute: typeof AuthenticatedDashboardTasksPrintRoute
  AuthenticatedDashboardTasksIndexRoute: typeof AuthenticatedDashboardTasksIndexRoute
}

const AuthenticatedDashboardTasksRouteChildren: AuthenticatedDashboardTasksRouteChildren =
  {
    AuthenticatedDashboardTasksTaskIdRoute:
      AuthenticatedDashboardTasksTaskIdRouteWithChildren,
    AuthenticatedDashboardTasksNewRoute: AuthenticatedDashboardTasksNewRoute,
    AuthenticatedDashboardTasksPrintRoute:
      AuthenticatedDashboardTasksPrintRoute,
    AuthenticatedDashboardTasksIndexRoute:
      AuthenticatedDashboardTasksIndexRoute,
  }

const AuthenticatedDashboardTasksRouteWithChildren =
  AuthenticatedDashboardTasksRoute._addFileChildren(
    AuthenticatedDashboardTasksRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardLocationsRoute: typeof AuthenticatedDashboardLocationsRouteWithChildren
  AuthenticatedDashboardMyWorkRoute: typeof AuthenticatedDashboardMyWorkRoute
  AuthenticatedDashboardNotificationsRoute: typeof AuthenticatedDashboardNotificationsRoute
  AuthenticatedDashboardOfficersRoute: typeof AuthenticatedDashboardOfficersRouteWithChildren
  AuthenticatedDashboardTasksRoute: typeof AuthenticatedDashboardTasksRouteWithChildren
  AuthenticatedDashboardUsersRoute: typeof AuthenticatedDashboardUsersRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardReportsPrintRoute: typeof AuthenticatedDashboardReportsPrintRoute
  AuthenticatedDashboardFieldReportsIndexRoute: typeof AuthenticatedDashboardFieldReportsIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardLocationsRoute:
      AuthenticatedDashboardLocationsRouteWithChildren,
    AuthenticatedDashboardMyWorkRoute: AuthenticatedDashboardMyWorkRoute,
    AuthenticatedDashboardNotificationsRoute:
      AuthenticatedDashboardNotificationsRoute,
    AuthenticatedDashboardOfficersRoute:
      AuthenticatedDashboardOfficersRouteWithChildren,
    AuthenticatedDashboardTasksRoute:
      AuthenticatedDashboardTasksRouteWithChildren,
    AuthenticatedDashboardUsersRoute: AuthenticatedDashboardUsersRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardReportsPrintRoute:
      AuthenticatedDashboardReportsPrintRoute,
    AuthenticatedDashboardFieldReportsIndexRoute:
      AuthenticatedDashboardFieldReportsIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DownloadRoute: DownloadRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
